server:
  port: 8090
  
spring:
  redis:
    database: 0
    timeout: 3000
    # 哨兵模式配置
#    sentinel:
#      master: mymaster
#      nodes: 10.211.55.3:26379,10.211.55.4:26380,10.211.55.5:26381
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000
    # redis-cluster 集群模式配置
    cluster:
      nodes: 10.211.55.3:8001,10.211.55.5:8006,10.211.55.4:8003,10.211.55.3:8002,10.211.55.5:8005,10.211.55.4:8004
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000
